project:
  type: website
  output-dir: _site
  preview:
    port: 5896
    browser: true
  render:
    - "*.qmd"
    - "!fragments/"
    - "!1-getting-started"
    - "!2-functions-packages"
    - "!3-creating-functions"
    - "!4-conditionals-testing"
    - "!5-iteration"
    - "!6-vectors"
    - "!7-strings"
    - "!8-data-frames"
    - "!9-data-wrangling"
    - "!10-data-visualization"
    - "!11-programming-with-data"
    - "!12-webscraping"
    - "!13-monte-carlo-methods"
    - "!14-final-review"
  resources:
    - "class/"
    - "rubrics/"
    - "slides/"
    - "data/"

website:
  title: EMSE 4571 / 6571
  image: images/logo.png
  site-url: https://p4a.seas.gwu.edu/2026-Spring/
  favicon: images/favicon.ico
  repo-url: https://github.com/emse-p4a-gwu/2026-Spring
  repo-actions: [edit, issue]
  description: 'Course website for Spring 2026 semester of the EMSE course "Intro. to Programming for Analytics" at GWU'
  search: true
  open-graph:
    locale: es_ES
    site-name: https://p4a.seas.gwu.edu/
  twitter-card:
    creator: "@johnhelveston"
    site: "@johnhelveston"
    image: "images/logo-square.png"
    card-style: summary
  sidebar:
    style: "docked"
    background: "dark"
    collapse-level: 1
    search: true
    contents:
      - text: Home
        icon: house-door-fill
        href: index.qmd
      - text: Syllabus
        icon: map-fill
        href: syllabus.qmd
      - text: Schedule
        icon: table
        href: schedule.qmd
      - text: Textbook
        icon: book-fill
        href: https://p4a.jhelvy.com/
      - text: Software
        icon: download
        href: software.qmd
      - text: FAQ
        icon: question-square-fill
        href: faq.qmd
      - text: References
        icon: bookmark-fill
        href: references.qmd
      - text: Autograder
        icon: list-check
        href: autograder.html
      - text: Slack
        icon: slack
        href: https://emse-p4a-s26.slack.com
      - text: "Schedule a call w/Prof. Helveston"
        icon: clock-fill
        href: https://jhelvy.appointlet.com/b/professor-helveston
      - section: Other
        icon: box-fill
        contents:
          - text: About
            icon: question-circle-fill
            href: about.qmd
          - text: License
            icon: award-fill
            href: LICENSE.qmd
          - text: Contact
            icon: envelope-fill
            href: mailto:jph@gwu.edu
          - text: Source files
            icon: github
            href: https://github.com/emse-p4a-gwu/2026-Spring
  page-footer:
    center:
      - text: "Â© 2026 John Paul Helveston {{< fa creative-commons-sa >}} <a href='LICENSE.html'><i class='fab fa-creative-commons'></i><i class='fab fa-creative-commons-by'></i><i class='fab fa-creative-commons-sa'></i></a><br><i class='far fa-calendar-alt'></i> {{< var weekday >}} | <i class='far fa-clock'></i> {{< var time >}} | <a href='{{< var room_url >}}'><i class='fa fa-map-marker-alt'></i> {{< var room >}}</a><br><a href='https://www.jhelvy.com'><i class='fas fa-user'></i> Dr. John Paul Helveston</a> | <a href='mailto:{{< var email >}}'><i class='fas fa-envelope'></i> {{< var email >}}</a> | <a href='{{< var repo >}}'><i class='fab fa-github'></i></a>"

format:
  html:
    theme: cosmo
    css: styles.css
    anchor-sections: true
    smooth-scroll: true
    link-external-newwindow: true
    link-external-icon: false
    # This is to include fontawesome icons
    include-in-header: "_includes/header.html"

filters:
    - schedule.lua
